import React,{Component} from 'react'
export default {
  firstnameplace: 'FirstName',
  lastnameplace: 'LastName',
  male:'Male',
  female:"Female",
  enterstreetnumber:'Enter Street Number',
  enterhousenumber:'Enter House Number',
  city:'City:',
  state:'State:',
  country:'Country:',
  addressline2:'Address	Line2:',
  addressline1:'Address	Line1:',
  email:'Email:',
  phonenumber:'Phone Number:',
  dob:'D.O.B:',
  star:'*',
  lastname:'LastName:',
  firstname:'FirstName:',
  gender:'Gender',
  patientid:'Patient Id:',
  enterpatientid:'Enter Patient Id',
  pleasefillthefields:'Please fill the fields marked as ',
  clear:'Clear',
  register:'Register',
  changelanguage:'Change Language: ',
  ds:'patientregitered', 
  issue:"Issue",
  search:'Search',
  patientid:"Patient_id:",
  searchbyfirstname:"Search By Firstname",
  enterpatientfirstname:"Enter Patient Firstname",
  searchbylastname:"Search By Lastname",
  enterpatientlastname:"Enter Patient Lastname",
  searchbydob:"Search by D.O.B",
  enterpatientdob:"Enter patient D.O.B",
  searchbyid:"Search By PatientId",
  searchByfirstnamelastnamedob:"Search by firstname,lastname and dob",
  enterpatientdob:"yyyy-mm-dd",
  searchByidfirstnamelastnamedob:"Search"
}